import { AuthProvider } from "@/provider/auth";
import dynamic from "next/dynamic";
import { ViewPropertyProvider } from "@/provider/property";
import { AddressProvider } from "@/provider/addresses";
import { ViewUnitsProvider } from "@/provider/viewunits";
import { ApplicationProvider } from "@/provider/application";
import { FileProvider } from "@/provider/file";
import { AgentProvider } from "@/provider/agents";
import { AmenitiesProvider } from "@/provider/amenities";

export const metadata = {
  title: "eKhaya",
  description: "Generated by Next.js",
};

// const withAuth

const DynamicRootLayout = dynamic(() => import("./layout"), { ssr: false });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  //const AuthenticatedComponent = RequireAuth(DynamicRootLayout);
  return (
    <AmenitiesProvider>
    <AgentProvider>
    <ApplicationProvider>
    <FileProvider>
    <ViewUnitsProvider>
    <AddressProvider>
    <ViewPropertyProvider>
      <AuthProvider>
        <html lang="en">
          <head>
            <meta charSet="UTF-8" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            />
            <title>{metadata.title}</title>
            <link rel="icon" href="/logo.png" />
            <meta name="description" content={metadata.description} />
          </head>
          <body style={{ margin: 0}}>{children}</body>
        </html>
      </AuthProvider>
    </ViewPropertyProvider>
    </AddressProvider>
    </ViewUnitsProvider>
    </FileProvider>
    </ApplicationProvider>
    </AgentProvider>
    </AmenitiesProvider>
  );
};

export default RootLayout;
