import { AuthProvider } from "@/provider/auth";
import dynamic from "next/dynamic";
import { ViewPropertyProvider } from "@/provider/property";
import { AddressProvider } from "@/provider/addresses";

export const metadata = {
  title: "eKhaya",
  description: "Generated by Next.js",
};

// const withAuth

const DynamicRootLayout = dynamic(() => import("./layout"), { ssr: false });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  //const AuthenticatedComponent = RequireAuth(DynamicRootLayout);
  return (
    <AddressProvider>
    <ViewPropertyProvider>
      <AuthProvider>
        <html lang="en">
          <head>
            <meta charSet="UTF-8" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            />
            <title>{metadata.title}</title>
            <link rel="icon" href="/logo.png" />
            <meta name="description" content={metadata.description} />
          </head>
          <body style={{ margin: 0 }}>{children}</body>
        </html>
      </AuthProvider>
    </ViewPropertyProvider>
    </AddressProvider>
  );
};

export default RootLayout;
